version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install conda
          command: |
            curl -s -o Miniconda3-latest-Linux-x86_64.sh "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
            bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            source $HOME/miniconda/bin/activate
            conda config --add channels conda-forge
      - python/install-deps
      - run:
          name: Install otwrapy
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            source $HOME/miniconda/bin/activate
            conda install -y otwrapy
      - run:
          name: Install LaTeX requirements
          command: |
            sudo apt-get install texlive-base
            sudo apt-get install texlive
            sudo apt-get install texlive-latex-extra
            sudo apt-get install texlive-latex-recommended
            sudo apt-get install texlive-fonts-recommended
            sudo apt-get install texlive-latex-extra
            sudo apt-get install texlive-science
            sudo apt-get install lmodern
            sudo apt-get install texlive-lang-french
            sudo apt-get install texlive-pstricks            
      - run:
          name: Test scripts
          command: bash ./.circleci/run_docker_linux.sh
      - run:
          name: Run Notebooks
          command: bash ./.circleci/run_Notebooks.sh

workflows:
  main:
    jobs:
      - build-and-test

